### ISSUE TITLE
The visualizations are not as good as they once were

### ISSUE THREAD

**Issue by aure** [AudioKit/Particles#1]
If anyone can restore this app to it former glory:

https://youtu.be/I-l8RALIoA4

That would be wonderful!

**Comment by aure** [comment]
And actually, the app crashes too, so there is definitely work to be done here!

**Comment by aure** [comment]
@ManjitBedi Care to take on this task next?

**Comment by ManjitBedi** [comment]
Possibly but having a crash log would help.   There are no steps listed to reproduce the crash.

**Comment by aure** [comment]
Not so much a crash as a visualization change/slowdown, at least that's what this particular issue was about.

**Comment by ManjitBedi** [comment]
Hi, I see;  I will have a think.  I don't know the Metal framework;  I do more coding in SceneKit / SpriteKit.  🤔

**Comment by warrenm** [comment]
I think the primary issue here, apart from performance and stability, is that the sample relies on undefined behavior in Metal to achieve some of its effects. Specifically, the `clearOnStep` property is set to `false` by default, which causes the renderer to reuse the contents of drawable textures, but Metal doesn't guarantee that drawables will be recycled in any particular order, nor that they won't be cleared between uses. This is what causes most of the glitchiness (where the simulation will seem to "jump backward" a few frames sometimes).

I've cleaned up the sample and tried to adhere a bit more closely to best practices in the `double-buffer` branch of my fork (https://github.com/warrenm/Particles/tree/double-buffer). It's not production-ready, but I think it behaves quite a bit better.

**Comment by aure** [comment]
Both the master branch and your double buffer branch crash my iPad Pro.  Any ideas?

```
2019-05-16 18:13:18.297352-0700 Particles[444:7685] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
Error: command buffer exited with error status.
	The Metal Performance Shaders operations encoded on it may not have completed.
	Error: 
	(null)
	Caused GPU Timeout Error (IOAF code 2)
	<AGXA9FamilyCommandBuffer: 0x119e284b0>
    label = <none> 
    device = <AGXA9XDevice: 0x10512c000>
        name = Apple A9X GPU 
    commandQueue = <AGXA9FamilyCommandQueue: 0x119e19a60>
        label = <none> 
        device = <AGXA9XDevice: 0x10512c000>
            name = Apple A9X GPU 
    retainedReferences = 1
```

**Comment by aure** [comment]
Works on my mini though so no worries.

**Comment by aure** [comment]
I think it looks just great now, so I'm going to close this issue!
