### ISSUE TITLE
I cannot get the project to compile

### ISSUE THREAD

**Issue by ManjitBedi** [AudioKit/Particles#3]
I am getting the following error at compile while using Xcode 10.1

```
AudioKit Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2.1 compiler:
```
I did set the Swift version to 4.2 in the pod file target(s).  I also deleted the derived data folder & the problem is still there.

**Comment by aure** [comment]
I am not surprised, this example has several problems that would come up even if you did get it to compile. We're going to have another look at modernizing this project, but unfortunately it probably won't be for a while unless a volunteer steps up. :-/

**Comment by ManjitBedi** [comment]
I see;  thanks for the reply/

**Comment by ManjitBedi** [comment]
I was able to build the project by deintegtsting the pod file; I updated the pod file to

```
  # Pods for Particles
  pod 'AudioKit', '~> 4.6.1'
```

& then doing a pod install & making some updates to the Swift for Swift 4.2

**Comment by ManjitBedi** [comment]
I created a pull request with the updated project.
