### ISSUE TITLE
I can't run the project and need help?

### ISSUE THREAD

**Issue by JayceBryce** [AudioKit/Particles#5]
Hello @aure @ManjitBedi @warrenm  ,

I'm trying to run this project but I keep getting errors that I can't? It's saying:

 The file “Pods-Particles.debug.xcconfig” couldn’t be opened because there is no such file. 

Could you please help out with this?

Thank you

**Comment by JayceBryce** [comment]
Is this project dead?

**Comment by warrenm** [comment]
This should be addressed with #6. You'll need to run `pod install` from the project root to get a version of AudioKit that is compatible with Swift 5.
